name: indonesia_address
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  indonesia_json:
    git:
      url: https://github.com/nashihu/indonesia_json.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
    # - packages/indonesia_json/assets/
    # - packages/indonesia_json/assets/kabupaten/
    # - packages/indonesia_json/assets/kecamatan/
    # - packages/indonesia_json/assets/kelurahan/